# Generated by Django 3.2.3 on 2023-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230711_1624'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='favorites_unique_cart_favorites',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='shoppingcart_unique_cart_favorites',
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorites'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shoppingcart'),
        ),
    ]
