# Generated by Django 3.2.3 on 2023-07-14 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230711_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Блюдо должно содержать хотя бы 1 ингредиент'), django.core.validators.MaxValueValidator(3000, 'Рецепт слишком сложный')], verbose_name='Количество ингредиентов'),
        ),
    ]
